"""Single source of truth for where the data lives.

Every notebook and script in this repository reads its inputs through this
module. Nothing hard-codes a relative path, so moving the data does not mean
editing thirty files: it means setting one environment variable.

The code ships with the repository, the data does not. Download the replication
dataset from Zenodo (see README), unpack it, and either place it at
``<repo>/data`` or point ``PV_AUDIT_DATA`` at wherever you put it::

    export PV_AUDIT_DATA=/scratch/pv-audit-data

Two directories, and the distinction matters when reproducing.

``data/source`` holds inputs that this repository does not produce: the
detection product, the registries, administrative boundaries, and the manual
annotations. Nothing here is regenerated by any script; it is the starting
point. The annotations sit here rather than under ``intermediate`` on purpose.
They are 31,853 human judgements, not a derived quantity, and no amount of
recomputation would recreate them.

``data/intermediate`` holds what the pipeline computes on the way to the paper's
numbers. It ships so that any single step can be re-run without replaying the
whole chain, and so that a reader can check one figure without downloading five
gigabytes of third-party dumps.

Most intermediate files are reproducible from ``data/source`` by the scripts in
``code/``, in the order given by REPRODUCE.md. Two are not, because their inputs
are bulk third-party downloads that this repository does not redistribute: the
OpenStreetMap PV extract needs the France ``.pbf``, and the imagery dates need
the IGN mosaicking graphs. ``data/MANIFEST.csv`` states, file by file, which is
which and what produces it. When in doubt, read the manifest rather than
guessing from the folder name.
"""

from __future__ import annotations

import os
from pathlib import Path

__all__ = ["REPO", "DATA", "SOURCE", "INTERMEDIATE", "FIGURES", "resolve", "describe"]


def _find_repo(start: Path | None = None) -> Path:
    """Walk up until the marker file that sits at the repository root."""
    start = (start or Path.cwd()).resolve()
    for parent in [start, *start.parents]:
        if (parent / "paths.py").exists() and (parent / "code").is_dir():
            return parent
    # Fall back to this file's own location, which is correct whenever the
    # module was imported rather than copied.
    return Path(__file__).resolve().parent


REPO: Path = _find_repo()
DATA: Path = Path(os.environ.get("PV_AUDIT_DATA", REPO / "data")).expanduser()
SOURCE: Path = DATA / "source"
INTERMEDIATE: Path = DATA / "intermediate"
FIGURES: Path = Path(os.environ.get("PV_AUDIT_FIGURES", REPO / "figures"))

# --------------------------------------------------------------------- source
# Inputs this repository consumes but does not produce.

#: Rooftop PV detections, already filtered to the <=36 kWp perimeter analysed in
#: the paper. Derived from release v3 of the OpenPVMapper database; the
#: unfiltered product is published separately and is not needed here.
DETECTIONS = SOURCE / "detections" / "dpvm_detections_filtered.geojson"

#: Public registry (RNI), flattened across the 2017-2025 annual publications.
RNI = SOURCE / "registries" / "rni_2017-2025_flatten.csv"

#: The nine annual snapshots the flattened file is built from. They are open
#: data, but they ship anyway: the platform republishes each vintage in place,
#: so a reader downloading them today would not necessarily get what this study
#: read. Shipping the snapshots is what makes build_rni.py reproducible rather
#: than merely re-runnable.
RNI_RAW = SOURCE / "registries" / "raw"

# ------------------------------------------------------- source: RTE derived
# Everything derived from the transmission system operator's grid-connection
# registry, and nothing else, lives under RTE_DERIVED. The raw per-installation
# extract is not redistributable; these files are the aggregates the audit
# consumes. Grouped in one folder so the perimeter of the redistribution
# agreement is a directory rather than a list. See its README.

RTE_DERIVED = SOURCE / "rte_derived"

#: Cumulative connected capacity and count per unit at each cutoff date. The
#: reference the audit compares against, and the input to the dating sweep.
RTE_CUTOFFS = RTE_DERIVED / "rte_departmental_cutoffs.csv"

#: Median registry coverage by operator type, within department. The
#: non-parametric counterpart of the fragmentation regression, and the only
#: form of that test a reader can re-run from this release.
RTE_ELD = RTE_DERIVED / "rte_eld_within_department.csv"

#: Capacity deciles for three illustrative units. An illustration of the size
#: distribution, not a basis for reconstructing it: the conversion anchoring
#: pools every consistent unit, which these three cannot stand in for. That
#: section of the analysis is documented as not reproducible from this release.
RTE_DECILES = RTE_DERIVED / "rte_capacity_deciles.csv"

RTE_MINIMAL = RTE_DERIVED / "rte_minimal.json"

#: Administrative boundaries. ``DEPARTEMENTS`` is the simplified geometry used
#: for maps; ``DEPARTEMENTS_DETAILED`` keeps the full outline where precision
#: matters. ``WORLD`` is the low-resolution basemap behind the maps.
DEPARTEMENTS = SOURCE / "boundaries" / "departements.geojson"
DEPARTEMENTS_DETAILED = SOURCE / "boundaries" / "departements_detailed.geojson"
WORLD = SOURCE / "boundaries" / "world_lowres.geojson"

#: Municipal geometries, 34,746 polygons, simplified to a 200 m tolerance and
#: shipped so that the truncation map does not need the full national boundary
#: dataset. At the scale that map is drawn, France being some 1,000 km across on
#: a page-width figure, 200 m is below one pixel: the simplification is invisible
#: in the output and removes a 1.1 GB third-party download.
COMMUNES = SOURCE / "boundaries" / "communes_simplified.gpkg"

#: Which operator serves each of the 34,746 municipalities. ``categorie`` is
#: Enedis, another distributor, mixed, or unlabelled, and it is the treatment
#: variable of the fragmentation regression.
#:
#: Its provenance is the operator registry's ``libelle_eic_gestionnaire`` field,
#: not Agence ORE, despite what earlier versions of the notebooks claimed. It
#: therefore lives under RTE_DERIVED and falls inside the redistribution
#: agreement, even though it carries no capacity and no count.
#:
#: Extracted from a 1.1 GB municipal geometry file that the analysis read with
#: ``ignore_geometry=True`` anyway; only the attribute table is shipped.
OPERATOR_BY_MUNICIPALITY = RTE_DERIVED / "operator_by_municipality.csv"

# -------------------------------------------------------- source: annotations
# The manual validation campaigns. Inputs, not derivatives: 31,853 human
# judgements that no script reconstructs.

#: One row per checked detection: was it real? Feeds precision.
PRECISION_POINTS = SOURCE / "annotations" / "precision_points.csv"

#: One row per independently located installation: did the detector find it?
#: Feeds recall. ``RECALL_SRC`` carries the provenance and estimated size of
#: each ground-truth point, which is what specification B weights by.
RECALL_POINTS = SOURCE / "annotations" / "recall_points.csv"
RECALL_SRC = SOURCE / "annotations" / "recall_src.csv"

#: Raw exports from the labelling platform, before aggregation into the two
#: files above. Kept so the aggregation step is checkable rather than assumed.
ANNOTATIONS_RAW = SOURCE / "annotations" / "raw"

#: Blind keys for the re-review campaign. The reviewer saw the samples without
#: knowing the original label; these files hold what the original label was.
KEY_PRECISION = ANNOTATIONS_RAW / "quality_assessment" / "key_precision.csv"
KEY_RECALL_FN = ANNOTATIONS_RAW / "quality_assessment" / "key_recall_fn.csv"

#: Manual date corrections for the municipalities the mosaicking graphs miss.
DATES_PATCH = SOURCE / "boundaries" / "dates_patch_communes.csv"

# --------------------------------------------------------- intermediate: eval
# Detection performance, measured on the annotated samples.

#: Per-unit scores and Beta parameters. The column ``recall_fn`` is fractional
#: by design: unreviewed false negatives carry a weight of one minus the
#: measured false-FN rate. See ``code/0_pipeline/evaluation/quality_assessment``.
EVAL_TABLE = INTERMEDIATE / "evaluation" / "table.csv"
OSM_SOURCES = INTERMEDIATE / "evaluation" / "osm_sources.csv"

#: Results of the annotation-quality tests: inter-rater agreement, whether OSM
#: ground truth behaves like manual annotation, and whether imagery vintage
#: shifts performance.
KAPPA_RESULTS = INTERMEDIATE / "evaluation" / "kappa_precision_results.csv"
SOURCE_CONCORDANCE = INTERMEDIATE / "evaluation" / "source_concordance_results.csv"
VINTAGE_EFFECT = INTERMEDIATE / "evaluation" / "vintage_effect_results.csv"
OSM_PV = INTERMEDIATE / "evaluation" / "osm_pv_france.geojson"
FN_VALIDITY = INTERMEDIATE / "evaluation" / "fn_validity.json"
FALSE_FN = INTERMEDIATE / "evaluation" / "false_fn_to_remove.csv"

# --------------------------------------------------- intermediate: postprocess

#: Imagery acquisition date per municipality, from the IGN mosaicking graphs.
IMAGERY_DATES = INTERMEDIATE / "postprocess" / "imagery_dates.geojson"

#: Corrected capacity posteriors per reporting unit.
RECALIBRATION = INTERMEDIATE / "postprocess" / "recalibration_departements.geojson"

COMPARISON_DEPT = INTERMEDIATE / "postprocess" / "comparison_departements.geojson"
COMPARISON_DEPT_RNI_BOTTOMUP = (
    INTERMEDIATE / "postprocess" / "comparison_departements_rni_bottomup.geojson"
)
COMPARISON_DEPT_RNI_TOTAL = (
    INTERMEDIATE / "postprocess" / "comparison_departements_rni_total.geojson"
)
COMPARISON_COMMUNES = INTERMEDIATE / "postprocess" / "comparison_communes.csv"
COMPARISON_COMMUNES_RNI = INTERMEDIATE / "postprocess" / "comparison_communes_rni.csv"

# -------------------------------------------------------- intermediate: audit

AUDIT_RTE = INTERMEDIATE / "audit" / "comparison_departements_rte.csv"
AUDIT_RNI_AGG = INTERMEDIATE / "audit" / "comparison_departements_rni_agg.csv"
AUDIT_RNI_BOTTOMUP = INTERMEDIATE / "audit" / "comparison_departements_rni_bottomup.csv"
SPECS_RTE = INTERMEDIATE / "audit" / "robustness_specs_rte.csv"
SPECS_RNI_AGG = INTERMEDIATE / "audit" / "robustness_specs_rni_agg.csv"
SPECS_RNI_BOTTOMUP = INTERMEDIATE / "audit" / "robustness_specs_rni_bottomup.csv"

#: Table S2 of the paper: the specification battery, unit by unit.
TABLE_S2 = INTERMEDIATE / "audit" / "table_s2_specifications.csv"

#: What forming the correction factor at a coarser scale costs.
CONVERGENCE_SCALES = INTERMEDIATE / "audit" / "estimation_convergence_scales.csv"
CONVERGENCE_REGIONS = INTERMEDIATE / "audit" / "estimation_convergence_regions.csv"

#: The public registry's privacy truncation, and the verdicts it changes.
TRUNCATION_SHARE = INTERMEDIATE / "audit" / "truncation_share_by_unit.csv"
TRUNCATION_STATUS = INTERMEDIATE / "audit" / "truncation_status_change.csv"

# --------------------------------------------------- intermediate: mechanisms

SHARE_ENEDIS = INTERMEDIATE / "mechanisms" / "share_enedis.csv"
ELD_BALANCE = INTERMEDIATE / "mechanisms" / "eld_balance_table.csv"
ELD_REGRESSION = INTERMEDIATE / "mechanisms" / "eld_regression_table.csv"
ELD_FLOOR_SENSITIVITY = INTERMEDIATE / "mechanisms" / "eld_floor_sensitivity.csv"
TAGGING = INTERMEDIATE / "mechanisms" / "mechanisms_tagging.csv"
TEMPORAL_LAG = INTERMEDIATE / "mechanisms" / "temporal_lag_departements.csv"
TEMPORAL_LAG_ABOVE = INTERMEDIATE / "mechanisms" / "temporal_lag_above_departements.csv"
TEMPORAL_LAG_ELD = INTERMEDIATE / "mechanisms" / "temporal_lag_eld_departements.csv"
TEMPORAL_SENSITIVITY = (
    INTERMEDIATE / "mechanisms" / "temporal_sensitivity_departements.csv"
)

# ------------------------------------------------------------- not shipped
# Third-party bulk downloads. Too large to redistribute and unchanged from
# their source, so the two steps that consume them are documented rather than
# runnable out of the box. See REPRODUCE.md, "Steps that need bulk downloads".

OSM_PBF = Path(os.environ.get("PV_AUDIT_OSM_PBF", SOURCE / "osm" / "france.osm.pbf"))
ADMIN_EXPRESS = Path(
    os.environ.get("PV_AUDIT_ADMIN_EXPRESS", SOURCE / "boundaries" / "admin-express")
)


def resolve(path: Path) -> Path:
    """Return ``path``, raising a message that says what to do if it is missing."""
    if path.exists():
        return path
    where = "PV_AUDIT_DATA" if str(DATA) in str(path) else "the repository"
    raise FileNotFoundError(
        f"{path} not found.\n"
        f"The replication dataset is not part of this repository. Download it "
        f"from Zenodo (see README), then either unpack it at {REPO / 'data'} or "
        f"set {where} to its location."
    )


def describe() -> str:
    """One-line status of every declared path, for a quick sanity check."""
    import sys

    rows = []
    for name, value in sorted(globals().items()):
        if name.isupper() and isinstance(value, Path) and name not in {"REPO", "DATA"}:
            mark = "ok " if value.exists() else "MISSING"
            rows.append(f"  {mark}  {name:28} {value}")
    header = f"repository : {REPO}\ndata       : {DATA}\nfigures    : {FIGURES}\n"
    text = header + "\n".join(rows)
    print(text, file=sys.stdout)
    return text


if __name__ == "__main__":
    describe()
