"""Generate COMPARISON.md: the three registry references side by side.

Consumes the ``robustness_specs_*`` tables written by the three audit notebooks.
Re-run it after any rerun of the chain. Its output is a descriptive companion to
the paper's supplementary material.

The point of the table is that the three audits are identical in every respect
except the reference they compare against: same corrected estimate, same
specification battery. Whatever changes between columns therefore belongs to the
registry, not to the method.
"""

import sys as _sys
from pathlib import Path as _Path


def _repo_root(start=_Path(__file__).resolve().parent):
    for parent in [start, *start.parents]:
        if (parent / "paths.py").exists() and (parent / "code").is_dir():
            return parent
    raise FileNotFoundError("this script must live inside the repository")


_sys.path.insert(0, str(_repo_root()))
import paths

import geopandas as gpd
import numpy as np
import pandas as pd

VARIANTS = [
    ('TSO connection data', paths.SPECS_RTE),
    ('Public registry, municipal (truncated)', paths.SPECS_RNI_BOTTOMUP),
    ('Public registry, total (truncation-corrected)', paths.SPECS_RNI_AGG),
]

# --- Reference column: the corrected national estimate with its interval ---
_t = pd.read_csv(paths.EVAL_TABLE, dtype={'dpt': str})
_rg = gpd.read_file(paths.RECALIBRATION, ignore_geometry=True)
_mm = _t.merge(_rg[['dpt', 'p_inst_raw']].assign(dpt=_rg.dpt.astype(str)), on='dpt')
_rng = np.random.default_rng(42)
_draws = np.zeros(10000)
for _, _r in _mm.iterrows():
    _draws += _r.p_inst_raw * _rng.beta(_r.alpha_precision, _r.beta_precision, 10000) \
                            / _rng.beta(_r.alpha_recall, _r.beta_recall, 10000)
_lo, _hi = np.percentile(_draws, [2.5, 97.5]) / 1e3
_mean = _draws.mean() / 1e3
ESTIMATE_COL = {
    'Date-matched registry (MWp)': f'{_mean:,.0f} [{_lo:,.0f}-{_hi:,.0f}] (corrected estimate)',
    'Corrected estimate (MWp)': f'{_mean:,.0f} [{_lo:,.0f}-{_hi:,.0f}]',
}

rows = {}
details = {}
for label, path in VARIANTS:
    rb = pd.read_csv(path, dtype={'dpt': str})
    tot, reg = rb.p_inst_mean.sum() / 1e3, rb.kWp_rte.sum() / 1e3
    hcb = rb[(rb.status_A == 'below') & (rb.status_B == 'below')].copy()
    hca = rb[(rb.status_A == 'above') & (rb.status_B == 'above')].copy()
    hcb['gap'] = (hcb.p_inst_mean - hcb.kWp_rte) / 1e3
    hcb['floor'] = (hcb.est_spec_min - hcb.kWp_rte) / 1e3
    hcb['coverage'] = hcb.kWp_rte / hcb.p_inst_mean
    vc = rb.status_A.value_counts()
    rel = (rb.p_inst_mean - rb.kWp_rte) / rb.p_inst_mean
    rows[label] = {
        'Date-matched registry (MWp)': f'{reg:,.0f}',
        'Corrected estimate (MWp)': f'{tot:,.0f}',
        'National surplus': f'{100 * (tot - reg) / reg:+.1f} %',
        'Verdicts under A (within/below/above)':
            f"{vc.get('within', 0)} / {vc.get('below', 0)} / {vc.get('above', 0)}",
        'Relative gap: median [IQR]':
            f'{rel.median():+.1%} [{rel.quantile(.25):+.1%}, {rel.quantile(.75):+.1%}]',
        'Hard core below (A and B)':
            f"{len(hcb)} units, {hcb.gap.sum():,.0f} MWp "
            f"(specification floor {hcb['floor'].sum():,.0f})",
        'of which conversion-sensitive':
            (f"{int(hcb.conversion_sensitive.sum())} "
             f"({', '.join(sorted(hcb.loc[hcb.conversion_sensitive, 'dpt']))})"
             if hcb.conversion_sensitive.any() else '0'),
        'Hard core above (negative control)':
            f"{len(hca)} units"
            + (f" (conversion-sensitive: "
               f"{', '.join(sorted(hca.loc[hca.conversion_sensitive, 'dpt']))})"
               if hca.conversion_sensitive.any() else ''),
        'Count-based concordance on the below core':
            str(rb.loc[(rb.status_A == 'below') & (rb.status_B == 'below'),
                       'status_D'].value_counts().to_dict()),
    }
    hcb_txt = ', '.join(f"{r.dpt} ({r.coverage:.0%})"
                        for _, r in hcb.sort_values('coverage').iterrows())
    details[label] = (hcb_txt, ', '.join(sorted(hca.dpt)))

idx = list(next(iter(rows.values())).keys())
rows = {'Corrected estimate (reference)': {k: ESTIMATE_COL.get(k, '-') for k in idx}, **rows}
HEADERS = [('Corrected estimate (reference)', None)] + VARIANTS

lines = [
    '# Registry references side by side',
    '',
    'Generated by `gen_comparison.py` from the `robustness_specs_*` tables.',
    '',
    'Three identical audits: same corrected estimate, same specification battery.',
    'Only the reference registry changes, so whatever differs between columns',
    'belongs to the registry rather than to the method. One caveat on granularity:',
    'the public registry is published annually, with 31 December attribution at',
    'best, so its date matching is structurally coarser than the connection data,',
    'which is dated to the day.',
    '',
    '| | ' + ' | '.join(label for label, _ in HEADERS) + ' |',
    '|---|' + '---|' * len(HEADERS),
]
for k in idx:
    lines.append(f"| {k} | " + ' | '.join(rows[label][k] for label, _ in HEADERS) + ' |')

lines += ['', '## Core membership, by increasing registry coverage', '']
for label, _ in VARIANTS:
    below, above = details[label]
    lines += [f'**{label}** — below: {below}', '', f'  above: {above}', '']

lines += [
    '## Reading',
    '',
    'The municipal-versus-total comparison isolates the **truncation bias**: same',
    'source, same chain, only the publication censoring changes, and the below',
    'core goes from 28 units to 7.',
    '',
    'The *above* tail of the total variant is largely attributable to the public',
    "registry's **year-end attribution**. At annual granularity the date matching",
    'absorbs connections made after the imagery was taken. That is a dating',
    'artefact of the published registry, not physical over-reporting, and it',
    'belongs to the same family as the truncation.',
    '',
]

out = _repo_root() / 'COMPARISON.md'
out.write_text('\n'.join(lines))
print(f'wrote {out} ({len(lines)} lines)')
